function trial0011g05 = readtsvCustom(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRIAL0011G05 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TRIAL0011G05 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  trial0011g05 = importfile("C:\Users\migue\Documents\Unsynced University\BiomechanicsOfMovement\KAP\T2 - 5 - Frontal Kick\Kinematic and Dynamic Data\trial_0011_g05.tsv", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Oct-2021 18:55:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [12, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 60);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Frame", "Time", "HeadX", "HeadY", "HeadZ", "L_ShoulderX", "L_ShoulderY", "L_ShoulderZ", "L_ElbowX", "L_ElbowY", "L_ElbowZ", "L_WristX", "L_WristY", "L_WristZ", "R_ShoulderX", "R_ShoulderY", "R_ShoulderZ", "R_ElbowX", "R_ElbowY", "R_ElbowZ", "R_WristX", "R_WristY", "R_WristZ", "L_HipX", "L_HipY", "L_HipZ", "L_KneeX", "L_KneeY", "L_KneeZ", "L_AnkleX", "L_AnkleY", "L_AnkleZ", "L_HeelX", "L_HeelY", "L_HeelZ", "L_Meta_VX", "L_Meta_VY", "L_Meta_VZ", "L_Toe_IIX", "L_Toe_IIY", "L_Toe_IIZ", "R_HipX", "R_HipY", "R_HipZ", "R_KneeX", "R_KneeY", "R_KneeZ", "R_AnkleX", "R_AnkleY", "R_AnkleZ", "R_HeelX", "R_HeelY", "R_HeelZ", "R_Meta_VX", "R_Meta_VY", "R_Meta_VZ", "R_Toe_IIX", "R_Toe_IIY", "R_Toe_IIZ", "VarName60"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName60", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName60", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Frame", "Time", "HeadX", "HeadY", "HeadZ", "L_ShoulderX", "L_ShoulderY", "L_ShoulderZ", "L_ElbowX", "L_ElbowY", "L_ElbowZ", "L_WristX", "L_WristY", "L_WristZ", "R_ShoulderX", "R_ShoulderY", "R_ShoulderZ", "R_ElbowX", "R_ElbowY", "R_ElbowZ", "R_WristX", "R_WristY", "R_WristZ", "L_HipX", "L_HipY", "L_HipZ", "L_KneeX", "L_KneeY", "L_KneeZ", "L_AnkleX", "L_AnkleY", "L_AnkleZ", "L_HeelX", "L_HeelY", "L_HeelZ", "L_Meta_VX", "L_Meta_VY", "L_Meta_VZ", "L_Toe_IIX", "L_Toe_IIY", "L_Toe_IIZ", "R_HipX", "R_HipY", "R_HipZ", "R_KneeX", "R_KneeY", "R_KneeZ", "R_AnkleX", "R_AnkleY", "R_AnkleZ", "R_HeelX", "R_HeelY", "R_HeelZ", "R_Meta_VX", "R_Meta_VY", "R_Meta_VZ", "R_Toe_IIX", "R_Toe_IIY", "R_Toe_IIZ"], "FillValue", 0);

% Import the data
trial0011g05 = readtable(filename, opts);

end