function modelgaitgroup72turn = importOutFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MODELGAITGROUP72TURN = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   MODELGAITGROUP72TURN = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   modelgaitgroup72turn = importfile('model_gait_group7_2turn.out', 3, 109);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/11/03 23:18:10

%% Initialize variables.
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: text (%s)
%	column12: text (%s)
%   column13: text (%s)
%	column14: text (%s)
%   column15: text (%s)
%	column16: text (%s)
%   column17: text (%s)
%	column18: text (%s)
%   column19: text (%s)
%	column20: text (%s)
%   column21: text (%s)
%	column22: text (%s)
%   column23: text (%s)
%	column24: text (%s)
%   column25: text (%s)
%	column26: text (%s)
%   column27: text (%s)
%	column28: text (%s)
%   column29: text (%s)
%	column30: text (%s)
%   column31: text (%s)
%	column32: text (%s)
%   column33: text (%s)
%	column34: text (%s)
%   column35: text (%s)
%	column36: text (%s)
%   column37: text (%s)
%	column38: text (%s)
%   column39: text (%s)
%	column40: text (%s)
%   column41: text (%s)
%	column42: text (%s)
%   column43: text (%s)
%	column44: text (%s)
%   column45: text (%s)
%	column46: text (%s)
%   column47: text (%s)
%	column48: text (%s)
%   column49: text (%s)
%	column50: text (%s)
%   column51: text (%s)
%	column52: text (%s)
%   column53: text (%s)
%	column54: text (%s)
%   column55: text (%s)
%	column56: text (%s)
%   column57: text (%s)
%	column58: text (%s)
%   column59: text (%s)
%	column60: text (%s)
%   column61: text (%s)
%	column62: text (%s)
%   column63: text (%s)
%	column64: text (%s)
%   column65: text (%s)
%	column66: text (%s)
%   column67: text (%s)
%	column68: text (%s)
%   column69: text (%s)
%	column70: text (%s)
%   column71: text (%s)
%	column72: text (%s)
%   column73: text (%s)
%	column74: text (%s)
%   column75: text (%s)
%	column76: text (%s)
%   column77: text (%s)
%	column78: text (%s)
%   column79: text (%s)
%	column80: text (%s)
%   column81: text (%s)
%	column82: text (%s)
%   column83: text (%s)
%	column84: text (%s)
%   column85: text (%s)
%	column86: text (%s)
%   column87: text (%s)
%	column88: text (%s)
%   column89: text (%s)
%	column90: text (%s)
%   column91: text (%s)
%	column92: text (%s)
%   column93: text (%s)
%	column94: text (%s)
%   column95: text (%s)
%	column96: text (%s)
%   column97: text (%s)
%	column98: text (%s)
%   column99: text (%s)
%	column100: text (%s)
%   column101: text (%s)
%	column102: text (%s)
%   column103: text (%s)
%	column104: text (%s)
%   column105: text (%s)
%	column106: text (%s)
%   column107: text (%s)
%	column108: text (%s)
%   column109: text (%s)
%	column110: text (%s)
%   column111: text (%s)
%	column112: text (%s)
%   column113: text (%s)
%	column114: text (%s)
%   column115: text (%s)
%	column116: text (%s)
%   column117: text (%s)
%	column118: text (%s)
%   column119: text (%s)
%	column120: text (%s)
%   column121: text (%s)
%	column122: text (%s)
%   column123: text (%s)
%	column124: text (%s)
%   column125: text (%s)
%	column126: text (%s)
%   column127: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10f%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%17s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{2} = strtrim(dataArray{2});
dataArray{3} = strtrim(dataArray{3});
dataArray{4} = strtrim(dataArray{4});
dataArray{5} = strtrim(dataArray{5});
dataArray{6} = strtrim(dataArray{6});
dataArray{7} = strtrim(dataArray{7});
dataArray{8} = strtrim(dataArray{8});
dataArray{9} = strtrim(dataArray{9});
dataArray{10} = strtrim(dataArray{10});
dataArray{11} = strtrim(dataArray{11});
dataArray{12} = strtrim(dataArray{12});
dataArray{13} = strtrim(dataArray{13});
dataArray{14} = strtrim(dataArray{14});
dataArray{15} = strtrim(dataArray{15});
dataArray{16} = strtrim(dataArray{16});
dataArray{17} = strtrim(dataArray{17});
dataArray{18} = strtrim(dataArray{18});
dataArray{19} = strtrim(dataArray{19});
dataArray{20} = strtrim(dataArray{20});
dataArray{21} = strtrim(dataArray{21});
dataArray{22} = strtrim(dataArray{22});
dataArray{23} = strtrim(dataArray{23});
dataArray{24} = strtrim(dataArray{24});
dataArray{25} = strtrim(dataArray{25});
dataArray{26} = strtrim(dataArray{26});
dataArray{27} = strtrim(dataArray{27});
dataArray{28} = strtrim(dataArray{28});
dataArray{29} = strtrim(dataArray{29});
dataArray{30} = strtrim(dataArray{30});
dataArray{31} = strtrim(dataArray{31});
dataArray{32} = strtrim(dataArray{32});
dataArray{33} = strtrim(dataArray{33});
dataArray{34} = strtrim(dataArray{34});
dataArray{35} = strtrim(dataArray{35});
dataArray{36} = strtrim(dataArray{36});
dataArray{37} = strtrim(dataArray{37});
dataArray{38} = strtrim(dataArray{38});
dataArray{39} = strtrim(dataArray{39});
dataArray{40} = strtrim(dataArray{40});
dataArray{41} = strtrim(dataArray{41});
dataArray{42} = strtrim(dataArray{42});
dataArray{43} = strtrim(dataArray{43});
dataArray{44} = strtrim(dataArray{44});
dataArray{45} = strtrim(dataArray{45});
dataArray{46} = strtrim(dataArray{46});
dataArray{47} = strtrim(dataArray{47});
dataArray{48} = strtrim(dataArray{48});
dataArray{49} = strtrim(dataArray{49});
dataArray{50} = strtrim(dataArray{50});
dataArray{51} = strtrim(dataArray{51});
dataArray{52} = strtrim(dataArray{52});
dataArray{53} = strtrim(dataArray{53});
dataArray{54} = strtrim(dataArray{54});
dataArray{55} = strtrim(dataArray{55});
dataArray{56} = strtrim(dataArray{56});
dataArray{57} = strtrim(dataArray{57});
dataArray{58} = strtrim(dataArray{58});
dataArray{59} = strtrim(dataArray{59});
dataArray{60} = strtrim(dataArray{60});
dataArray{61} = strtrim(dataArray{61});
dataArray{62} = strtrim(dataArray{62});
dataArray{63} = strtrim(dataArray{63});
dataArray{64} = strtrim(dataArray{64});
dataArray{65} = strtrim(dataArray{65});
dataArray{66} = strtrim(dataArray{66});
dataArray{67} = strtrim(dataArray{67});
dataArray{68} = strtrim(dataArray{68});
dataArray{69} = strtrim(dataArray{69});
dataArray{70} = strtrim(dataArray{70});
dataArray{71} = strtrim(dataArray{71});
dataArray{72} = strtrim(dataArray{72});
dataArray{73} = strtrim(dataArray{73});
dataArray{74} = strtrim(dataArray{74});
dataArray{75} = strtrim(dataArray{75});
dataArray{76} = strtrim(dataArray{76});
dataArray{77} = strtrim(dataArray{77});
dataArray{78} = strtrim(dataArray{78});
dataArray{79} = strtrim(dataArray{79});
dataArray{80} = strtrim(dataArray{80});
dataArray{81} = strtrim(dataArray{81});
dataArray{82} = strtrim(dataArray{82});
dataArray{83} = strtrim(dataArray{83});
dataArray{84} = strtrim(dataArray{84});
dataArray{85} = strtrim(dataArray{85});
dataArray{86} = strtrim(dataArray{86});
dataArray{87} = strtrim(dataArray{87});
dataArray{88} = strtrim(dataArray{88});
dataArray{89} = strtrim(dataArray{89});
dataArray{90} = strtrim(dataArray{90});
dataArray{91} = strtrim(dataArray{91});
dataArray{92} = strtrim(dataArray{92});
dataArray{93} = strtrim(dataArray{93});
dataArray{94} = strtrim(dataArray{94});
dataArray{95} = strtrim(dataArray{95});
dataArray{96} = strtrim(dataArray{96});
dataArray{97} = strtrim(dataArray{97});
dataArray{98} = strtrim(dataArray{98});
dataArray{99} = strtrim(dataArray{99});
dataArray{100} = strtrim(dataArray{100});
dataArray{101} = strtrim(dataArray{101});
dataArray{102} = strtrim(dataArray{102});
dataArray{103} = strtrim(dataArray{103});
dataArray{104} = strtrim(dataArray{104});
dataArray{105} = strtrim(dataArray{105});
dataArray{106} = strtrim(dataArray{106});
dataArray{107} = strtrim(dataArray{107});
dataArray{108} = strtrim(dataArray{108});
dataArray{109} = strtrim(dataArray{109});
dataArray{110} = strtrim(dataArray{110});
dataArray{111} = strtrim(dataArray{111});
dataArray{112} = strtrim(dataArray{112});
dataArray{113} = strtrim(dataArray{113});
dataArray{114} = strtrim(dataArray{114});
dataArray{115} = strtrim(dataArray{115});
dataArray{116} = strtrim(dataArray{116});
dataArray{117} = strtrim(dataArray{117});
dataArray{118} = strtrim(dataArray{118});
dataArray{119} = strtrim(dataArray{119});
dataArray{120} = strtrim(dataArray{120});
dataArray{121} = strtrim(dataArray{121});
dataArray{122} = strtrim(dataArray{122});
dataArray{123} = strtrim(dataArray{123});
dataArray{124} = strtrim(dataArray{124});
dataArray{125} = strtrim(dataArray{125});
dataArray{126} = strtrim(dataArray{126});
dataArray{127} = strtrim(dataArray{127});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
modelgaitgroup72turn = table(dataArray{1:end-1}, 'VariableNames', {'Time','VarName2','VarName3','VarName4','VarName5','Body001','VarName7','VarName8','VarName9','VarName10','VarName11','VarName12','VarName13','VarName14','Body002','VarName16','VarName17','VarName18','VarName19','VarName20','VarName21','VarName22','VarName23','Body003','VarName25','VarName26','VarName27','VarName28','VarName29','VarName30','VarName31','VarName32','Body004','VarName34','VarName35','VarName36','VarName37','VarName38','VarName39','VarName40','VarName41','Body005','VarName43','VarName44','VarName45','VarName46','VarName47','VarName48','VarName49','VarName50','Body006','VarName52','VarName53','VarName54','VarName55','VarName56','VarName57','VarName58','VarName59','Body007','VarName61','VarName62','VarName63','VarName64','VarName65','VarName66','VarName67','VarName68','Body008','VarName70','VarName71','VarName72','VarName73','VarName74','VarName75','VarName76','VarName77','Body009','VarName79','VarName80','VarName81','VarName82','VarName83','VarName84','VarName85','VarName86','Body010','VarName88','VarName89','VarName90','VarName91','VarName92','VarName93','VarName94','VarName95','Body011','VarName97','VarName98','VarName99','VarName100','VarName101','VarName102','VarName103','VarName104','Body012','VarName106','VarName107','VarName108','VarName109','VarName110','VarName111','VarName112','VarName113','Body013','VarName115','VarName116','VarName117','VarName118','VarName119','VarName120','VarName121','VarName122','Body014','VarName124','VarName125','VarName126','VarName127'});

